tp1/grails-app/domain/fr/mbds/tp1/User.groovy
package fr.mbds.tp1

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String firstName
    String lastName
    String username
    String password
    String picture;
    String email;
    boolean enabled = true
    boolean accountExpired = false
    boolean accountLocked = false
    boolean passwordExpired = false

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    String toString() {
        return lastName + " " + firstName
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
        email email: true
        firstName nullable: false, blank: false
        lastName nullable: false, blank: false
    }

    static mapping = {
	    password column: '`password`'
    }
}

tp1/grails-app/controllers/fr/mbds/tp1/UserController.groovy
package fr.mbds.tp1

import grails.validation.ValidationException

import static org.springframework.http.HttpStatus.*

class UserController {

  UserService userService
  RoleService roleService
  PersistanceService persistanceService

  static allowedMethods = [saveuser: "POST", update: "PUT", delete: "DELETE"]

  def index(Integer max) {
    params.max = Math.min(max ?: 12, 100)
    respond userService.list(params), model: [userCount: userService.count()]
  }

  def show(Long id) {
    respond userService.get(id)
  }

  def create() {
  }

  def saveuser() {
    if (params.createUser == null) return;

    def imageFile = request.getFile('picture')

    try {
      params.picture = persistanceService.saveImageFile(imageFile)
    } catch(Exception e) {
      return [hasError: true, message: e.getMessage()]
    }

    User user = new User(params);

    if (!user.validate()) {
      return [hasError: true, message: "Paramètre invalide"]
    }

    try {
      userService.save(user)
      roleService.affectPlayerRole(user)
    } catch (ValidationException e) {
      return [hasError: true, message: e.getMessage()]
    }

    request.withFormat {
      form multipartForm {
        flash.message = "${params.username} a bien été crée"
        redirect user
      }
      '*' { respond user, [status: CREATED] }
    }
  }

  def edit(Long id) {
    respond userService.get(id)
  }

  def update(User user) {
    if (user == null) {
      notFound()
      return
    }

    try {
      userService.save(user)
    } catch (ValidationException e) {
      respond user.errors, view: 'edit'
      return
    }

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
        redirect user
      }
      '*' { respond user, [status: OK] }
    }
  }

  def delete(Long id) {
    if (id == null) {
      notFound()
      return
    }

    userService.delete(id)

    render status: NO_CONTENT
  }

  protected void notFound() {
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NOT_FOUND }
    }
  }
}

tp1/grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="main"/>
  <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
  <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<div id="create-user" class="container-fluid" role="main">
  <div class="container">
    <h1 class="h1">Créer un joueur</h1>
    <g:if test="${hasError}">
      <div class="alert alert-danger alert-dismissible" role="alert">
        ${hasError}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </g:if>
    <g:if test="${isCreated}">
      <div class="alert alert-success alert-dismissible" role="alert">
        ${message}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </g:if>
    <hr class="my-3"/>
    <g:uploadForm action="saveuser" method="POST" class="was-validated">
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="username">Identifiant</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fas fa-user-shield"></i>
              </span>
            </div>
            <input
              type="text"
              name="username"
              id="username"
              class="form-control"
              placeholder="identifiant"
              required />
          </div>

        </div>
        <div class="form-group col-md-6">
          <label for="password">Mot de passe</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fas fa-lock"></i>
              </span>
            </div>
            <input
              type="password"
              name="password"
              id="password"
              class="form-control"
              placeholder="Mot de passe"
              required />
          </div>

        </div>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fas fa-envelope"></i>
            </span>
          </div>
          <input
            type="email"
            name="email"
            id="email"
            class="form-control"
            placeholder="Email"
            required />
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="lastName">Nom</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fas fa-id-card"></i>
              </span>
            </div>
            <input
              type="text"
              name="lastName"
              id="lastName"
              class="form-control"
              placeholder="Nom"
              required />
          </div>
        </div>
        <div class="form-group col-md-6">
          <label for="firstName">Prénom</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fas fa-id-card"></i>
              </span>
            </div>
            <input
              type="text"
              name="firstName"
              id="firstName"
              class="form-control"
              placeholder="Prénom"
              required />
          </div>

        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-12">
          <div class="custom-file">
            <input
              type="file"
              name="picture"
              id="picture"
              class="custom-file-input"
              accept="image/png, image/jpeg"
              size="19999"
              lang="fr"
              required />
            <label
              for="picture"
              class="custom-file-label">Choisir une image de profil</label>
          </div>
        </div>
      </div>
      <button class="btn btn-primary" type="submit" name="createUser">Créer</button>
    </g:uploadForm>
  </div>
</div>
</body>
</html>

tp1/grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="main"/>
  <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
  <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
  <div id="edit-user" class="container-fluid scaffold-edit" role="main">
    <div class="container">
      <h1 class="h1">Modifier un joueur</h1>
      <g:if test="${flash.message}">
        <div class="alert alert-success alert-dismissible" role="alert">
          ${flash.message}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </g:if>
      <g:if test="${hasError}">
        <div class="alert alert-danger alert-dismissible" role="alert">
          ${hasError}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </g:if>
      <hr class="my-3"/>
      <g:uploadForm resource="${this.user}" method="PUT" class="was-validated">
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="username">Identifiant</label>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">
                  <i class="fas fa-user-shield"></i>
                </span>
              </div>
              <input
                type="text"
                name="username"
                id="username"
                class="form-control"
                placeholder="identifiant"
                value="${this.user.username}"
                required />
            </div>

          </div>
          <div class="form-group col-md-6">
            <label for="password">Mot de passe</label>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">
                  <i class="fas fa-lock"></i>
                </span>
              </div>
              <input
                type="password"
                name="password"
                id="password"
                class="form-control"
                placeholder="Mot de passe"
                required />
            </div>

          </div>
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fas fa-envelope"></i>
              </span>
            </div>
            <input
              type="email"
              name="email"
              id="email"
              class="form-control"
              placeholder="Email"
              value="${this.user.email}"
              required />
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="lastName">Nom</label>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">
                  <i class="fas fa-id-card"></i>
                </span>
              </div>
              <input
                type="text"
                name="lastName"
                id="lastName"
                class="form-control"
                placeholder="Nom"
                value="${this.user.lastName}"
                required />
            </div>
          </div>
          <div class="form-group col-md-6">
            <label for="firstName">Prénom</label>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">
                  <i class="fas fa-id-card"></i>
                </span>
              </div>
              <input
                type="text"
                name="firstName"
                id="firstName"
                class="form-control"
                placeholder="Prénom"
                value="${this.user.firstName}"
                required />
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-12">
            <div class="custom-file">
              <input
                type="file"
                name="picture"
                id="picture"
                class="custom-file-input"
                accept="image/png, image/jpeg"
                size="128000"
                value="${this.user.picture}"
                 />
              <label
                for="picture"
                class="custom-file-label">Choisir une image de profil</label>
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
            <div class="form-check">
              <g:checkBox
                class="form-check-input"
                name="accountExpired"
                value="${this.user.accountExpired}"
                id="accountExpired" />
              <label class="form-check-label" for="accountExpired">
                Compte expiré
              </label>
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
            <div class="form-check">
              <g:checkBox
                class="form-check-input"
                name="passwordExpired"
                value="${this.user.passwordExpired}"
                id="passwordExpired" />
              <label class="form-check-label" for="passwordExpired">
                Mot de passe expiré
              </label>
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
            <div class="form-check">
              <g:checkBox
                class="form-check-input"
                name="accountLocked"
                value="${this.user.accountLocked}"
                id="accountLocked" />
              <label class="form-check-label" for="accountLocked">
                Vérouiller le compte
              </label>
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
            <div class="form-check">
              <g:checkBox
                class="form-check-input"
                name="enabled"
                value="${this.user.enabled}"
                id="enabled" />
              <label class="form-check-label" for="enabled">
                Activer le compte
              </label>
            </div>
          </div>
        </div>
        <button class="btn btn-primary" type="submit" name="createUser">Modifier</button>
      </g:uploadForm>
    </div>
  </div>
</body>
</html>

tp1/grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
      <div id="list-user" class="container-fluid" role="main">
        <div class="container">
          <h1 class="h1">Liste des joueurs</h1>
          <g:if test="${flash.message}">
            <div class="alert alert-success alert-dismissible" role="alert">
              ${flash.message}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          </g:if>
          <g:if test="${hasError}">
            <div class="alert alert-danger alert-dismissible" role="alert">
              ${hasError}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          </g:if>
          <hr class="my-3"/>
          <div class="card-columns">
            <g:each var="user" in="${userList.sort { it.lastName }}">
              <div class="card">
                <g:if test="${user.picture != null && user.picture != ''}">
                  <img src="${user.picture}" alt="${user.lastName} ${user.firstName}" class="card-img-top"/>
                </g:if>
                <div class="card-body">
                  <h5 class="card-title text-capitalize"><span class="text-muted">${user.lastName}</span> ${user.firstName}</h5>
                  <div class="d-flex justify-content-between flex-wrap">
                    <g:link class="btn btn-primary" action="show" resource="${user}">Voir</g:link>
                    <g:link class="btn btn-warning" action="edit" resource="${user}">Modifier</g:link>
                    <g:link class="btn btn-danger delete-on-click" action="delete" resource="${user}">Supprimer</g:link>
                  </div>
                </div>
              </div>
            </g:each>
          </div>
          <nav>
            <ul class="pagination">
              <g:paginateBootsrap max="12" total="${userCount ?: 0}" />
            </ul>
          </nav>
        </div>
      </div>
    </body>
</html>

tp1/grails-app/views/user/show.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="main"/>
  <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
  <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<div id="show-user" class="container-fluid" role="main">
  <div class="container">
    <h1 class="h1">
      <span class="">Profil de <span class="text-capitalize text-muted">${this.user.lastName} ${this.user.firstName}</span></span>
    </h1>
    <g:if test="${flash.message}">
      <div class="alert alert-success alert-dismissible" role="alert">
        ${flash.message}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </g:if>
    <g:if test="${hasError}">
      <div class="alert alert-danger alert-dismissible" role="alert">
        ${hasError}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </g:if>
    <hr class="my-3"/>
    <div class="row">
      <div class="col-4">
        <div class="card">
          <img class="card-img-top" src="${this.user.picture}" alt="">
          <ul class="list-group list-group-flush">
            <li href="#" class="list-group-item list-group-item-action">
              <p class="card-text"><small class="text-muted">Données personnelles</small></p>
              <div class="row">
                <div class="col">
                  <p class="card-text"><span class="badge badge-secondary">Nom</span></p>
                </div>
                <div class="col">
                  <p class="card-text text-right text-capitalize">${this.user.lastName}</p>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <p class="card-text"><span class="badge badge-secondary">Prénom</span></p>
                </div>
                <div class="col">
                  <p class="card-text text-right text-capitalize">${this.user.firstName}</p>
                </div>
              </div>
            </li>
            <li href="#" class="list-group-item list-group-item-action">
              <p class="card-text"><small class="text-muted">Informations de contact</small></p>
              <div class="row">
                <div class="col">
                  <p class="card-text"><span class="badge badge-secondary">Email</span></p>
                </div>
                <div class="col">
                  <p class="card-text text-right">${this.user.email}</p>
                </div>
              </div>

            </li>
            <li href="#" class="list-group-item list-group-item-action">
              <p class="card-text"><small class="text-muted">Autres informations</small></p>
              <div class="row">
                <div class="col">
                  <p class="card-text"><span class="badge badge-success">Compte activé</span></p>
                </div>
                <div class="col">
                  <p class="card-text text-right">${this.user.enabled ? "Oui" : "Non"}</p>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <p class="card-text"><span class="badge badge-secondary">Compte bloqué</span></p>
                </div>
                <div class="col">
                  <p class="card-text text-right">${this.user.accountLocked ? "Oui" : "Non"}</p>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <p class="card-text"><span class="badge badge-secondary">Mot de passe expiré</span></p>
                </div>
                <div class="col">
                  <p class="card-text text-right">${this.user.passwordExpired ? "Oui" : "Non"}</p>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <p class="card-text"><span class="badge badge-secondary">Compte expiré</span></p>
                </div>
                <div class="col">
                  <p class="card-text text-right">${this.user.accountExpired ? "Oui" : "Non"}</p>
                </div>
              </div>
            </li>
          </ul>
          <div class="card-body">
            <g:link
              class="btn btn-warning card-link"
              action="edit"
              resource="${this.user}">Modifier</g:link>
            <g:link
              class="btn btn-danger card-link delete-on-click"
              action="delete"
              resource="${this.user}">Supprimer</g:link>
          </div>
        </div>
      </div>
      <div class="col">
        <canvas id="matchChart" width="400" height="400"></canvas>
      </div>
    </div>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    var ctx = document.getElementById('matchChart').getContext('2d');

    var color = Chart.helpers.color;
    var barChartData = {
      labels: ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet'],
      datasets: [{
        type: 'line',
        label: 'Victoire',
        backgroundColor: color(window.chartColors.red).alpha(0.2).rgbString(),
        borderColor: window.chartColors.red,
        data: [
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor())
        ]
      }, {
        type: 'line',
        label: 'Defaite',
        backgroundColor: color(window.chartColors.green).alpha(0.2).rgbString(),
        borderColor: window.chartColors.green,
        data: [
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor()),
          Math.abs(randomScalingFactor())
        ]
      }]
    };

    // Define a plugin to provide data labels
    Chart.plugins.register({
      afterDatasetsDraw: function(chart) {
        var ctx = chart.ctx;

        chart.data.datasets.forEach(function(dataset, i) {
          var meta = chart.getDatasetMeta(i);
          if (!meta.hidden) {
            meta.data.forEach(function(element, index) {
              // Draw the text in black, with the specified font
              ctx.fillStyle = 'rgb(0, 0, 0)';

              var fontSize = 16;
              var fontStyle = 'normal';
              var fontFamily = 'Helvetica Neue';
              ctx.font = Chart.helpers.fontString(fontSize, fontStyle, fontFamily);

              // Just naively convert to string for now
              var dataString = dataset.data[index].toString();

              // Make sure alignment settings are correct
              ctx.textAlign = 'center';
              ctx.textBaseline = 'middle';

              var padding = 5;
              var position = element.tooltipPosition();
              ctx.fillText(dataString, position.x, position.y - (fontSize / 2) - padding);
            });
          }
        });
      }
    });

    window.myBar = new Chart(ctx, {
      type: 'bar',
      data: barChartData,
      options: {
        responsive: true,
        title: {
          display: true,
          text: 'Ratio victoir/defaite'
        },
        scales: {
          xAxes: [{
            gridLines: {
              display:false
            }
          }],
          yAxes: [{
            gridLines: {
              display:false
            }
          }]
        }
      }
    });
  });
</script>
<asset:javascript src="utils.js"/>
</body>
</html>