tp1/grails-app/domain/fr/mbds/tp1/Match.groovy
package fr.mbds.tp1

class Match {

  User winner;
  User looser;
  int winnerScore;
  int looserScore;

  static constraints = {
    winner nullable: false
    looser nullable: false
  }
}

tp1/grails-app/controllers/fr/mbds/tp1/MatchController.groovy
package fr.mbds.tp1

import grails.validation.ValidationException

import static org.springframework.http.HttpStatus.*

class MatchController {

  MatchService matchService

  static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    respond matchService.list(params), model: [matchCount: matchService.count()]
  }

  def show(Long id) {
    respond matchService.get(id)
  }

  def create() {
    [user: User]
  }

  def save(Match match) {
    if (match == null) {
      notFound()
      return
    }

    try {
      matchService.save(match)
    } catch (ValidationException e) {
      respond match.errors, view: 'create'
      return
    }

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.created.message', args: [message(code: 'match.label', default: 'Match'), match.id])
        redirect match
      }
      '*' { respond match, [status: CREATED] }
    }
  }

  def edit(Long id) {
    [match: matchService.get(id), user: User]
  }

  def update(Match match) {
    if (match == null) {
      notFound()
      return
    }

    try {
      matchService.save(match)
    } catch (ValidationException e) {
      respond match.errors, view: 'edit'
      return
    }

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.updated.message', args: [message(code: 'match.label', default: 'Match'), match.id])
        redirect match
      }
      '*' { respond match, [status: OK] }
    }
  }

  def delete(Long id) {
    if (id == null) {
      notFound()
      return
    }

    matchService.delete(id)

    request.withFormat {
      form multipartForm {
        flash.message = "Le match a bien été supprimé"
        redirect action: "index", method: "GET"
      }
      '*' { render status: NO_CONTENT }
    }
  }

  protected void notFound() {
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'match.label', default: 'Match'), params.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NOT_FOUND }
    }
  }
}

tp1/grails-app/views/match/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'match.label', default: 'Match')}" />
        <title>Enregistrer un nouveau match</title>
    </head>
    <body>
        <div id="create-match" class="container" role="main">
            <h1>Enregistrer un nouveau match</h1>
            <g:if test="${flash.message}">
                <div class="alert alert-success alert-dismissible" role="alert">
                    ${flash.message}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </g:if>
            <g:if test="${hasError}">
                <div class="alert alert-danger alert-dismissible" role="alert">
                    ${hasError}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </g:if>
            <g:form class="was-validated" action="save" method="POST">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="author">Gagnant</label>
                        <g:select class="form-control text-capitalize"
                                  id="winner"
                                  name="winner.id"
                                  from="${user.list().sort { it.lastName }}"
                                  optionKey="id"/>
                        <div class="invalid-feedback">Selectionner un gagant</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="winnerScore">Score</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-star-half-alt"></i>
                                </span>
                            </div>
                            <input
                              type="number"
                              name="winnerScore"
                              id="winnerScore"
                              min="0"
                              value="0"
                              class="form-control">
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="target">Perdant</label>
                        <g:select class="form-control text-capitalize"
                                  id="looser"
                                  name="looser.id"
                                  from="${user.list().sort { it.lastName }}"
                                  optionKey="id"/>
                        <div class="invalid-feedback">Selectionner un perdant</div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="looserScore">Score</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-star-half-alt"></i>
                                </span>
                            </div>
                            <input
                              type="number"
                              name="looserScore"
                              id="looserScore"
                              min="0"
                              value="0"
                              class="form-control">
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Enregister</button>
            </g:form>
        </div>
    </body>
</html>

tp1/grails-app/views/match/edit.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="main"/>
  <g:set var="entityName" value="${message(code: 'match.label', default: 'Match')}"/>
  <title>Modifier un match</title>
</head>

<body>
<div id="edit-match" class="container" role="main">
  <h1>Modifier un match</h1>
  <g:if test="${flash.message}">
    <div class="alert alert-success alert-dismissible" role="alert">
      ${flash.message}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <g:if test="${hasError}">
    <div class="alert alert-danger alert-dismissible" role="alert">
      ${hasError}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <g:form class="was-validated" action="save" method="POST">
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="author">Gagnant</label>
        <g:select class="form-control text-capitalize"
                  id="winner"
                  name="winner.id"
                  from="${user.list().sort { it.lastName }}"
                  value="${match.winner.id}"
                  optionKey="id"/>
        <div class="invalid-feedback">Selectionner un gagant</div>
      </div>

      <div class="form-group col-md-6">
        <label for="winnerScore">Score</label>

        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fas fa-star-half-alt"></i>
            </span>
          </div>
          <input
            type="number"
            name="winnerScore"
            id="winnerScore"
            min="0"
            value="${match.winnerScore}"
            class="form-control">
        </div>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="target">Perdant</label>
        <g:select class="form-control text-capitalize"
                  id="looser"
                  name="looser.id"
                  from="${user.list().sort { it.lastName }}"
                  value="${match.looser.id}"
                  optionKey="id"/>
        <div class="invalid-feedback">Selectionner un perdant</div>
      </div>

      <div class="form-group col-md-6">
        <label for="looserScore">Score</label>

        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fas fa-star-half-alt"></i>
            </span>
          </div>
          <input
            type="number"
            name="looserScore"
            id="looserScore"
            min="0"
            value="${match.looserScore}"
            class="form-control">
        </div>
      </div>
    </div>
    <button class="btn btn-primary" type="submit">Enregister</button>
  </g:form>
</div>
</body>
</html>

tp1/grails-app/views/match/index.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="main"/>
  <g:set var="entityName" value="${message(code: 'match.label', default: 'Match')}"/>
  <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>
<body>
<div id="list-match" class="container" role="main">
  <h1>Liste des matchs</h1>
  <g:if test="${flash.message}">
    <div class="alert alert-success alert-dismissible" role="alert">
      ${flash.message}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <g:if test="${hasError}">
    <div class="alert alert-danger alert-dismissible" role="alert">
      ${hasError}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <div class="list-group table-match">
    <g:each var="match" in="${matchList}">
      <div class="list-group-item list-group-item-action d-flex justify-content-between">
        <div class="d-flex justify-content-center">
          <div class="text-capitalize text-right">
            <g:link class="h3" resource="${match.winner}" action="show">
              <span class="badge badge-primary text-capitalize">
                ${match.winner.firstName} ${match.winner.lastName}
              </span>
              <img
                style='width:55px'
                class='img-fluid rounded-circle'
                src="${match.winner.picture}"
                alt="${match.winner}"/>
            </g:link>
          </div>
          <div class="text-center h1 table-match-scores">${match.winnerScore} <span class="text-black-50">-</span> ${match.looserScore}</div>
          <div class="text-capitalize text-left">
            <g:link class="h3" resource="${match.looser}" action="show">
              <img
                style='width:55px'
                class='img-fluid rounded-circle'
                src="${match.looser.picture}"
                alt="${match.looser}"/>
              <span class="badge badge-secondary text-capitalize">
                ${match.looser.firstName} ${match.looser.lastName}
              </span>
            </g:link>
          </div>
        </div>
        <small class="h4 d-flex justify-content-end align-items-center">
          <g:link class="btn btn-primary mr-2" resource="${match}" action="show"><i class="fas fa-eye"></i></g:link>
          <g:link class="btn btn-warning mr-2" resource="${match}" action="edit"><i class="fas fa-pencil-alt"></i></g:link>
          <g:link
            resource="${match}"
            action="delete"
            class="delete-on-click btn btn-danger">
            <i class="fas fa-trash-alt"></i>
          </g:link>
        </small>
      </div>
    </g:each>
  </div>

  <nav>
    <ul class="pagination">
      <g:paginateBootsrap total="${matchCount ?: 0}"/>
    </ul>
  </nav>
</div>
</body>
</html>

tp1/grails-app/views/match/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'match.label', default: 'Match')}" />
        <title>Détails du match</title>
    </head>
    <body>
        <div id="show-match" class="container" role="main">
            <h1>Détails du match</h1>
            <g:if test="${flash.message}">
                <div class="alert alert-success alert-dismissible" role="alert">
                    ${flash.message}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </g:if>
            <g:if test="${hasError}">
                <div class="alert alert-danger alert-dismissible" role="alert">
                    ${hasError}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </g:if>
            <div class="list-group table-match">
                <div class="list-group-item list-group-item-dark list-group-item-action d-flex flex-column justify-content-between">
                    <div class="d-flex justify-content-between">
                        <div class="text-capitalize text-right">
                            <g:link class="h3" resource="${match.winner}" action="show">
                                <span class="badge badge-primary text-capitalize">
                                    ${match.winner.firstName} ${match.winner.lastName}
                                </span>
                                <img
                                  style='width:55px'
                                  class='img-fluid rounded-circle'
                                  src="${match.winner.picture}"
                                  alt="${match.winner}"/>
                            </g:link>
                        </div>
                        <div class="text-center h1 table-match-scores">${match.winnerScore} <span class="text-black-50">-</span> ${match.looserScore}</div>
                        <div class="text-capitalize text-left">
                            <g:link class="h3" resource="${match.looser}" action="show">
                                <img
                                  style='width:55px'
                                  class='img-fluid rounded-circle'
                                  src="${match.looser.picture}"
                                  alt="${match.looser}"/>
                                <span class="badge badge-secondary text-capitalize">
                                    ${match.looser.firstName} ${match.looser.lastName}
                                </span>
                            </g:link>
                        </div>
                    </div>
                    <small class="h4 d-flex justify-content-center align-items-center mt-4">
                        <g:link class="btn btn-warning mr-2" resource="${match}" action="edit"><i class="fas fa-pencil-alt"></i> Modifier</g:link>
                        <g:link
                          resource="${match}"
                          action="delete"
                          class="delete-on-click btn btn-danger">
                            <i class="fas fa-trash-alt"></i> Supprimer
                        </g:link>
                    </small>
                </div>
            </div>
        </div>
    </body>
</html>