tp1/grails-app/domain/fr/mbds/tp1/Message.groovy
package fr.mbds.tp1

class Message {
  User author;
  User target;
  String message;
  Boolean isReaded = false;

  static constraints = {
    author nullable: false, blank: false
    target nullable: false, blank: false
  }
}

tp1/grails-app/controllers/fr/mbds/tp1/MessageController.groovy
package fr.mbds.tp1

import grails.validation.ValidationException
import org.springframework.http.HttpStatus

import static org.springframework.http.HttpStatus.*

class MessageController {

  MessageService messageService

  static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

  def index(Integer max) {
    params.max = Math.min(max ?: 10, 100)
    respond messageService.list(params), model: [messageCount: messageService.count()]
  }

  def show(Long id) {
    Message message = messageService.get(id)

    if (!message.isReaded) {
      message.isReaded = true
      try {
        messageService.save(message)
      } catch (ValidationException e) {
        respond message.errors, view: 'index', model: [messageCount: messageService.count(), hasError: "Impossible de consulter le message"]
        return
      }
    }
    respond message
  }

  def create() {
    [user: User]
  }

  def save(Message message) {
    if (message == null) {
      notFound()
      return
    }

    try {
      messageService.save(message)
    } catch (ValidationException | Exception e) {
      respond(message.errors,  view: 'create', model: [user: User, hasError: e.getMessage()])
      return
    }

    request.withFormat {
      form multipartForm {
        flash.message = "Le message a bien été crée"
        redirect(action: 'index')
      }
      '*' { respond message, [status: CREATED] }
    }
  }

  def edit(Long id) {
    [message: messageService.get(id), user: User]
  }

  def update(Message message) {
    if (message == null) {
      notFound()
      return
    }

    try {
      messageService.save(message)
    } catch (ValidationException e) {
      respond message.errors, view: 'edit'
      return
    }

    request.withFormat {
      form multipartForm {
        flash.message = "Le message à bien été modifié"
        redirect message
      }
      '*' { respond message, [status: OK] }
    }
  }

  def delete(Long id) {
    if (id == null) {
      notFound()
      return
    }

    messageService.delete(id)

    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.deleted.message', args: [message(code: 'message.label', default: 'Message'), id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NO_CONTENT }
    }
  }

  protected void notFound() {
    request.withFormat {
      form multipartForm {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'message.label', default: 'Message'), params.id])
        redirect action: "index", method: "GET"
      }
      '*' { render status: NOT_FOUND }
    }
  }
}

tp1/grails-app/views/message/create.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="main"/>
  <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}"/>
  <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<div id="create-message" class="container" role="main">
  <h1>Créer un message</h1>
  <g:if test="${flash.message}">
    <div class="alert alert-success alert-dismissible" role="alert">
      ${flash.message}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <g:if test="${hasError}">
    <div class="alert alert-danger alert-dismissible" role="alert">
      ${hasError}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <g:form class="was-validated" action="save" method="POST">
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="author">Auteur</label>
        <g:select class="form-control text-capitalize"
                  id="author"
                  name="author.id"
                  from="${user.list().sort { it.lastName }}"
                  optionKey="id"/>
        <div class="invalid-feedback">Selectionner un auteur</div>
      </div>
      <div class="form-group col-md-6">
        <label for="target">Destinataire</label>
        <g:select class="form-control text-capitalize"
                  id="target"
                  name="target.id"
                  from="${user.list().sort { it.lastName }}"
                  optionKey="id"/>
        <div class="invalid-feedback">Selectionner un auteur</div>
      </div>
    </div>
    <div class="form-group">
      <label for="message">Message</label>
      <textarea
        class="form-control"
        id="message"
        name="message"
        rows="3"
        maxlength="254"
        required></textarea>
    </div>
    <button class="btn btn-primary" type="submit">Créer</button>
  </g:form>
</div>
</body>
</html>

tp1/grails-app/views/message/edit.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="main"/>
  <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}"/>
  <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<div id="create-message" class="container" role="main">
  <h1>Modifier un message</h1>
  <g:if test="${flash.message}">
    <div class="alert alert-success alert-dismissible" role="alert">
      ${flash.message}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <g:if test="${hasError}">
    <div class="alert alert-danger alert-dismissible" role="alert">
      ${hasError}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <g:form class="was-validated" resource="${this.message}"method="PUT">
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="author">Auteur</label>
        <g:select class="form-control text-capitalize"
                  id="author"
                  name="author.id"
                  from="${user.list().sort { it.lastName }}"
                  value="${message.author.id}"
                  optionKey="id"/>
        <div class="invalid-feedback">Selectionner un auteur</div>
      </div>
      <div class="form-group col-md-6">
        <label for="target">Destinataire</label>
        <g:select class="form-control text-capitalize"
                  id="target"
                  name="target.id"
                  from="${user.list().sort { it.lastName }}"
                  value="${message.target.id}"
                  optionKey="id"/>
        <div class="invalid-feedback">Selectionner un auteur</div>
      </div>
    </div>
    <div class="form-group">
      <label for="message">Message</label>
      <textarea
        class="form-control"
        id="message"
        name="message"
        rows="3"
        maxlength="254"
        required>${message.message}</textarea>
    </div>
    <button class="btn btn-primary" type="submit">Modifier</button>
  </g:form>
</div>
</body>
</html>

tp1/grails-app/views/message/index.gsp
<!DOCTYPE html>
<html>
<head>
  <meta name="layout" content="main"/>
  <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}"/>
  <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div id="list-message" class="container" role="main">
  <h1 class="h1">Liste des messages</h1>
  <g:if test="${flash.message}">
    <div class="alert alert-success alert-dismissible" role="alert">
      ${flash.message}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <g:if test="${hasError}">
    <div class="alert alert-danger alert-dismissible" role="alert">
      ${hasError}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </g:if>
  <div class="list-group">
    <g:each var="message" in="${messageList}">
      <div class="message-container list-group-item list-group-item-action flex-column align-items-start">
        <g:if test="${!message.isReaded}">
          <div class="message-indicator bg-primary"></div>
        </g:if>
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">
            De <g:link resource="${message.author}" action="show">
              <img
                style='width:25px'
                class='img-fluid rounded-circle'
                src="${message.author.picture}"
                alt="${message.author}"/>
                <span class="badge badge-primary text-capitalize">
                  ${message.author.firstName} ${message.author.lastName.charAt(0)}.
                </span>
            </g:link> à <g:link resource="${message.target}" action="show">
              <img
                style='width:25px'
                class='img-fluid rounded-circle'
                src="${message.target.picture}"
                alt="${message.target}"/>
              <span class="badge badge-secondary text-capitalize">
                ${message.target.firstName} ${message.target.lastName.charAt(0)}.
              </span>
            </g:link>
          </h5>
          <small>29 août</small>
        </div>
        <hr class="border border-light mt-1 mb-3">
        <p class="mb-1 text-black-50">${message.message}</p>
        <small class="h4 d-flex justify-content-end">
          <g:link class="badge badge-pill badge-primary mr-2" resource="${message}" action="show"><i class="fas fa-envelope-open"></i></g:link>
          <g:link class="badge badge-pill badge-warning mr-2" resource="${message}" action="edit"><i class="fas fa-pencil-alt"></i></g:link>
          <g:link
            resource="${message}"
            action="delete"
            class="delete-on-click badge badge-pill badge-danger">
            <i class="fas fa-trash-alt"></i>
          </g:link>
        </small>
      </div>
    </g:each>
  </div>
  <nav class="mt-4">
    <ul class="pagination">
      <g:paginateBootsrap total="${messageCount ?: 0}"/>
    </ul>
  </nav>
</div>
</body>
</html>

tp1/grails-app/views/message/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'message.label', default: 'Message')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="show-message" class="container" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="alert alert-success alert-dismissible" role="alert">
                    ${flash.message}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </g:if>
            <g:if test="${hasError}">
                <div class="alert alert-danger alert-dismissible" role="alert">
                    ${hasError}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </g:if>
            <div class="list-group">
                <div class="message-container list-group-item list-group-item-action flex-column align-items-start">
                    <g:if test="${!message.isReaded}">
                        <div class="message-indicator bg-primary"></div>
                    </g:if>
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">
                            De <g:link resource="${message.author}" action="show">
                            <img
                              style='width:25px'
                              class='img-fluid rounded-circle'
                              src="${message.author.picture}"
                              alt="${message.author}"/>
                            <span class="badge badge-primary text-capitalize">
                                ${message.author.firstName} ${message.author.lastName.charAt(0)}.
                            </span>
                        </g:link> à <g:link resource="${message.target}" action="show">
                            <img
                              style='width:25px'
                              class='img-fluid rounded-circle'
                              src="${message.target.picture}"
                              alt="${message.target}"/>
                            <span class="badge badge-secondary text-capitalize">
                                ${message.target.firstName} ${message.target.lastName.charAt(0)}.
                            </span>
                        </g:link>
                        </h5>
                        <small>29 août</small>
                    </div>
                    <hr class="border border-light mt-1 mb-3">
                    <p class="mb-1 text-black-50">${message.message}</p>
                    <small class="h4 d-flex justify-content-end">
                        <g:link
                          class="badge badge-pill badge-warning mr-2"
                          resource="${message}" action="edit"><i class="fas fa-pencil-alt"></i></g:link>
                        <g:link
                          resource="${message}"
                          action="delete"
                          class="delete-on-click badge badge-pill badge-danger">
                            <i class="fas fa-trash-alt"></i>
                        </g:link>
                    </small>
                </div>
            </div>
        </div>
    </body>
</html>